In [1]:
import pandas as pd
import numpy as np
import py_pcha
from py_pcha import PCHA
import matplotlib.pyplot as plt
from numpy.matlib import repmat

In [2]:
data=pd.read_csv("/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/us-states.csv")
data

,date,geoid,state,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,2020-01-21,USA-53,Washington,1,0.14,0.00,0,0.00,0.00
1,2020-01-22,USA-53,Washington,0,0.14,0.00,0,0.00,0.00
2,2020-01-23,USA-53,Washington,0,0.14,0.00,0,0.00,0.00
3,2020-01-24,USA-53,Washington,0,0.14,0.00,0,0.00,0.00
4,2020-01-24,USA-17,Illinois,1,0.14,0.00,0,0.00,0.00
...,...,...,...,...,...,...,...,...,...
22669,2021-04-18,USA-06,California,1610,2510.14,6.35,45,82.14,0.21
22670,2021-04-18,USA-05,Arkansas,45,185.57,6.15,1,4.71,0.16
22671,2021-04-18,USA-04,Arizona,711,600.00,8.24,2,11.50,0.16
22672,2021-04-18,USA-02,Alaska,0,161.57,22.09,0,0.17,0.02
22673,2021-04-18,USA-01,Alabama,270,345.00,7.04,0,11.14,0.23

In [3]:
data = data.drop(columns = ["geoid"])
data

,date,state,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,2020-01-21,Washington,1,0.14,0.00,0,0.00,0.00
1,2020-01-22,Washington,0,0.14,0.00,0,0.00,0.00
2,2020-01-23,Washington,0,0.14,0.00,0,0.00,0.00
3,2020-01-24,Washington,0,0.14,0.00,0,0.00,0.00
4,2020-01-24,Illinois,1,0.14,0.00,0,0.00,0.00
...,...,...,...,...,...,...,...,...
22669,2021-04-18,California,1610,2510.14,6.35,45,82.14,0.21
22670,2021-04-18,Arkansas,45,185.57,6.15,1,4.71,0.16
22671,2021-04-18,Arizona,711,600.00,8.24,2,11.50,0.16
22672,2021-04-18,Alaska,0,161.57,22.09,0,0.17,0.02
22673,2021-04-18,Alabama,270,345.00,7.04,0,11.14,0.23

In [4]:
cols = data.columns.tolist()
cols

['date',
 'state',
 'cases',
 'cases_avg',
 'cases_avg_per_100k',
 'deaths',
 'deaths_avg',
 'deaths_avg_per_100k']

In [5]:
cols = [cols[1]] + [cols[0]] + cols[2:]
cols

['state',
 'date',
 'cases',
 'cases_avg',
 'cases_avg_per_100k',
 'deaths',
 'deaths_avg',
 'deaths_avg_per_100k']

In [6]:
data = data[cols] 
data

,state,date,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,Washington,2020-01-21,1,0.14,0.00,0,0.00,0.00
1,Washington,2020-01-22,0,0.14,0.00,0,0.00,0.00
2,Washington,2020-01-23,0,0.14,0.00,0,0.00,0.00
3,Washington,2020-01-24,0,0.14,0.00,0,0.00,0.00
4,Illinois,2020-01-24,1,0.14,0.00,0,0.00,0.00
...,...,...,...,...,...,...,...,...
22669,California,2021-04-18,1610,2510.14,6.35,45,82.14,0.21
22670,Arkansas,2021-04-18,45,185.57,6.15,1,4.71,0.16
22671,Arizona,2021-04-18,711,600.00,8.24,2,11.50,0.16
22672,Alaska,2021-04-18,0,161.57,22.09,0,0.17,0.02
22673,Alabama,2021-04-18,270,345.00,7.04,0,11.14,0.23

In [7]:
data = data.rename(columns={"state": "id"})
data

,id,date,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,Washington,2020-01-21,1,0.14,0.00,0,0.00,0.00
1,Washington,2020-01-22,0,0.14,0.00,0,0.00,0.00
2,Washington,2020-01-23,0,0.14,0.00,0,0.00,0.00
3,Washington,2020-01-24,0,0.14,0.00,0,0.00,0.00
4,Illinois,2020-01-24,1,0.14,0.00,0,0.00,0.00
...,...,...,...,...,...,...,...,...
22669,California,2021-04-18,1610,2510.14,6.35,45,82.14,0.21
22670,Arkansas,2021-04-18,45,185.57,6.15,1,4.71,0.16
22671,Arizona,2021-04-18,711,600.00,8.24,2,11.50,0.16
22672,Alaska,2021-04-18,0,161.57,22.09,0,0.17,0.02
22673,Alabama,2021-04-18,270,345.00,7.04,0,11.14,0.23

In [8]:
data.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/CovidDataMatrix.csv', index = False)

In [10]:
data_states = data["id"]
data_states = set(data_states)
data_states = list(data_states)

In [11]:
data_var = list(data.columns[2:])

In [15]:
states = data_states
variables = data_var

df = pd.DataFrame()

for i in range(len(states)):
    state = data.loc[data['id'] == ""+states[i]]
    newdf = state.iloc[0:1]
    
    for j in range(len(variables)):
        variable_name = variables[j]
        for k in range(state.shape[0]):
            var_name = str(k)
            value = state.iloc[k][""+variable_name]
            newdf[var_name+variable_name] = value
    
    df = pd.concat([df, newdf], ignore_index=True)
    
df

<ipython-input-15-f237a6595f77>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf[var_name+variable_name] = value

,id,date,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k,0cases,1cases,...,444deaths_avg_per_100k,445deaths_avg_per_100k,446deaths_avg_per_100k,447deaths_avg_per_100k,448deaths_avg_per_100k,449deaths_avg_per_100k,450deaths_avg_per_100k,451deaths_avg_per_100k,452deaths_avg_per_100k,453deaths_avg_per_100k
0,Tennessee,2020-03-05,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Massachusetts,2020-02-01,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Washington,2020-01-21,1,0.14,0.00,0,0.00,0.00,1,0,...,0.09,0.09,0.09,0.08,0.08,0.09,0.08,0.1,0.1,0.1
3,Oklahoma,2020-03-06,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Kentucky,2020-03-06,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,New York,2020-03-01,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Mississippi,2020-03-11,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Vermont,2020-03-07,1,0.14,0.02,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Northern Mariana Islands,2020-03-28,2,0.29,0.53,0,0.00,0.00,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Kansas,2020-03-07,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Oregon,2020-02-28,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Guam,2020-03-15,3,0.43,0.25,0,0.00,0.00,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Nevada,2020-03-05,2,0.29,0.01,0,0.00,0.00,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Idaho,2020-03-13,1,0.14,0.01,0,0.00,0.00,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Alaska,2020-03-12,1,0.14,0.02,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Arizona,2020-01-26,1,0.14,0.00,0,0.00,0.00,1,0,...,0.21,0.17,0.22,0.18,0.16,NaN,NaN,NaN,NaN,NaN
16,New Jersey,2020-03-04,1,0.14,0.00,0,0.00,0.00,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Wyoming,2020-03-11,1,0.14,0.02,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Illinois,2020-01-24,1,0.14,0.00,0,0.00,0.00,1,0,...,0.16,0.17,0.18,0.18,0.18,0.19,0.18,NaN,NaN,NaN
19,Colorado,2020-03-05,2,0.29,0.00,0,0.00,0.00,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Pennsylvania,2020-03-06,2,0.29,0.00,0,0.00,0.00,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Connecticut,2020-03-08,1,0.14,0.00,0,0.00,0.00,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,2020-03-02,2,0.29,0.00,0,0.00,0.00,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,South Carolina,2020-03-06,2,0.29,0.01,0,0.00,0.00,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,West Virginia,2020-03-17,1,0.14,0.01,0,0.00,0.00,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Nebraska,2020-02-17,10,1.43,0.07,0,0.00,0.00,10,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,New Mexico,2020-03-11,4,0.57,0.03,0,0.00,0.00,4,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Ohio,2020-03-09,3,0.43,0.00,0,0.00,0.00,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Montana,2020-03-13,4,0.57,0.05,0,0.00,0.00,4,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,California,2020-01-25,1,0.14,0.00,0,0.00,0.00,1,1,...,0.24,0.27,0.25,0.23,0.22,0.21,NaN,NaN,NaN,NaN
30,South Dakota,2020-03-10,5,0.71,0.08,1,0.14,0.02,5,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Missouri,2020-03-07,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Virgin Islands,2020-03-14,1,0.14,0.13,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Maryland,2020-03-05,3,0.43,0.01,0,0.00,0.00,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Louisiana,2020-03-09,1,0.14,0.00,0,0.00,0.00,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,North Carolina,2020-03-03,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Minnesota,2020-03-06,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,North Dakota,2020-03-11,1,0.14,0.02,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,District of Columbia,2020-03-07,1,0.14,0.02,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Michigan,2020-03-10,2,0.29,0.00,0,0.00,0.00,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Hawaii,2020-03-06,1,0.14,0.01,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Maine,2020-03-12,1,0.14,0.01,0,0.00,0.00,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Puerto Rico,2020-03-13,3,0.43,0.01,0,0.00,0.00,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Wisconsin,2020-02-05,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Virginia,2020-03-07,1,0.14,0.00,0,0.00,0.00,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Iowa,2020-03-08,3,0.43,0.01,0,0.00,0.00,3,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Rhode Island,2020-03-01,2,0.29,0.03,0,0.00,0.00,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Utah,2020-02-25,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Florida,2020-03-01,2,0.29,0.00,0,0.00,0.00,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,New Hampshire,2020-03-02,1,0.14,0.01,0,0.00,0.00,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Arkansas,2020-03-11,1,0.14,0.00,0,0.00,0.00,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Alabama,2020-03-13,6,0.86,0.02,0,0.00,0.00,6,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Indiana,2020-03-06,1,0.14,0.00,0,0.00,0.00,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Texas,2020-02-12,1,0.14,0.00,0,0.00,0.00,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Delaware,2020-03-11,1,0.14,0.01,0,0.00,0.00,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_data = df.fillna(0)

In [17]:
df_data = df_data.drop(columns = data_var)
df_data

,id,date,0cases,1cases,2cases,3cases,4cases,5cases,6cases,7cases,...,444deaths_avg_per_100k,445deaths_avg_per_100k,446deaths_avg_per_100k,447deaths_avg_per_100k,448deaths_avg_per_100k,449deaths_avg_per_100k,450deaths_avg_per_100k,451deaths_avg_per_100k,452deaths_avg_per_100k,453deaths_avg_per_100k
0,Tennessee,2020-03-05,1,0,0,2,1,3,1,10,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
1,Massachusetts,2020-02-01,1,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
2,Washington,2020-01-21,1,0,0,0,0,0,0,0,...,0.09,0.09,0.09,0.08,0.08,0.09,0.08,0.1,0.1,0.1
3,Oklahoma,2020-03-06,1,0,0,0,1,0,0,1,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
4,Kentucky,2020-03-06,1,0,3,1,2,0,4,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
5,New York,2020-03-01,1,0,1,9,11,22,45,17,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
6,Mississippi,2020-03-11,1,0,5,0,4,2,9,13,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
7,Vermont,2020-03-07,1,0,0,0,1,0,0,3,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
8,Northern Mariana Islands,2020-03-28,2,0,0,0,4,2,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
9,Kansas,2020-03-07,1,0,0,0,0,4,1,2,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
10,Oregon,2020-02-28,1,0,1,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
11,Guam,2020-03-15,3,0,0,5,4,2,1,12,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
12,Nevada,2020-03-05,2,0,0,2,0,0,3,4,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
13,Idaho,2020-03-13,1,4,0,0,4,2,12,8,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
14,Alaska,2020-03-12,1,0,0,0,2,3,3,3,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
15,Arizona,2020-01-26,1,0,0,0,0,0,0,0,...,0.21,0.17,0.22,0.18,0.16,0.00,0.00,0.0,0.0,0.0
16,New Jersey,2020-03-04,1,1,2,0,2,5,4,8,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
17,Wyoming,2020-03-11,1,0,1,1,0,7,5,2,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
18,Illinois,2020-01-24,1,0,0,0,0,0,1,0,...,0.16,0.17,0.18,0.18,0.18,0.19,0.18,0.0,0.0,0.0
19,Colorado,2020-03-05,2,6,0,0,4,5,17,15,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
20,Pennsylvania,2020-03-06,2,2,2,4,2,4,6,19,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
21,Connecticut,2020-03-08,1,1,0,1,3,5,9,6,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
22,Georgia,2020-03-02,2,0,0,0,1,4,4,6,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
23,South Carolina,2020-03-06,2,0,4,1,2,1,2,1,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
24,West Virginia,2020-03-17,1,1,3,3,4,4,0,23,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
25,Nebraska,2020-02-17,10,0,0,1,0,0,0,1,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
26,New Mexico,2020-03-11,4,2,4,3,4,4,2,5,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
27,Ohio,2020-03-09,3,0,1,1,8,13,11,13,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
28,Montana,2020-03-13,4,2,0,2,0,4,7,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
29,California,2020-01-25,1,1,0,0,0,0,1,0,...,0.24,0.27,0.25,0.23,0.22,0.21,0.00,0.0,0.0,0.0
30,South Dakota,2020-03-10,5,3,0,1,0,0,1,1,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
31,Missouri,2020-03-07,1,0,0,0,0,1,2,1,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
32,Virgin Islands,2020-03-14,1,0,1,0,1,0,3,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
33,Maryland,2020-03-05,3,0,0,2,1,3,4,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
34,Louisiana,2020-03-09,1,5,7,1,22,41,26,34,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
35,North Carolina,2020-03-03,1,0,0,1,0,0,5,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
36,Minnesota,2020-03-06,1,0,1,0,1,2,4,5,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
37,North Dakota,2020-03-11,1,0,0,0,0,0,4,2,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
38,District of Columbia,2020-03-07,1,0,3,0,6,0,0,6,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
39,Michigan,2020-03-10,2,0,10,13,8,20,1,11,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
40,Hawaii,2020-03-06,1,0,1,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
41,Maine,2020-03-12,1,1,1,9,5,15,11,9,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
42,Puerto Rico,2020-03-13,3,1,1,0,0,0,1,8,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
43,Wisconsin,2020-02-05,1,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
44,Virginia,2020-03-07,1,1,3,3,2,7,13,12,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
45,Iowa,2020-03-08,3,5,5,1,2,1,1,4,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
46,Rhode Island,2020-03-01,2,0,0,0,0,1,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
47,Utah,2020-02-25,1,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
48,Florida,2020-03-01,2,0,1,0,1,3,5,1,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
49,New Hampshire,2020-03-02,1,1,0,0,0,2,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
50,Arkansas,2020-03-11,1,5,1,2,7,6,0,11,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
51,Alabama,2020-03-13,6,6,11,6,10,12,27,28,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
52,Indiana,2020-03-06,1,0,1,2,2,5,1,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
53,Texas,2020-02-12,1,1,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0
54,Delaware,2020-03-11,1,3,0,0,3,1,8,10,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0

In [19]:
df_data = df_data.drop(['id', 'date'], axis=1)

In [20]:
df_num = df_data.to_numpy().T

In [21]:
for i in range(7):
    noc_val = i + 1
    XC, S, C, SSE, varexpl = PCHA(df_num, noc=noc_val, I = None, delta=0)
    
    S_df = pd.DataFrame(S)
    XC_df = pd.DataFrame(XC)
    
    S_df.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/CovidSMatrix'+ \
                str(noc_val)+'.csv', index = False, header = True)
    XC_df.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/CovidXCMatrix'+ \
                 str(noc_val)+'.csv', index = False, header = True)