In [1]:
import pandas as pd
import numpy as np
import py_pcha
from py_pcha import PCHA
import matplotlib.pyplot as plt
from numpy.matlib import repmat

In [2]:
data=pd.read_csv("/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/us-states.csv")
data

,date,geoid,state,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,2020-01-21,USA-53,Washington,1,0.14,0.00,0,0.00,0.00
1,2020-01-22,USA-53,Washington,0,0.14,0.00,0,0.00,0.00
2,2020-01-23,USA-53,Washington,0,0.14,0.00,0,0.00,0.00
3,2020-01-24,USA-53,Washington,0,0.14,0.00,0,0.00,0.00
4,2020-01-24,USA-17,Illinois,1,0.14,0.00,0,0.00,0.00
...,...,...,...,...,...,...,...,...,...
22669,2021-04-18,USA-06,California,1610,2510.14,6.35,45,82.14,0.21
22670,2021-04-18,USA-05,Arkansas,45,185.57,6.15,1,4.71,0.16
22671,2021-04-18,USA-04,Arizona,711,600.00,8.24,2,11.50,0.16
22672,2021-04-18,USA-02,Alaska,0,161.57,22.09,0,0.17,0.02
22673,2021-04-18,USA-01,Alabama,270,345.00,7.04,0,11.14,0.23

In [3]:
data = data.drop(columns = ["geoid"])
data

,date,state,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,2020-01-21,Washington,1,0.14,0.00,0,0.00,0.00
1,2020-01-22,Washington,0,0.14,0.00,0,0.00,0.00
2,2020-01-23,Washington,0,0.14,0.00,0,0.00,0.00
3,2020-01-24,Washington,0,0.14,0.00,0,0.00,0.00
4,2020-01-24,Illinois,1,0.14,0.00,0,0.00,0.00
...,...,...,...,...,...,...,...,...
22669,2021-04-18,California,1610,2510.14,6.35,45,82.14,0.21
22670,2021-04-18,Arkansas,45,185.57,6.15,1,4.71,0.16
22671,2021-04-18,Arizona,711,600.00,8.24,2,11.50,0.16
22672,2021-04-18,Alaska,0,161.57,22.09,0,0.17,0.02
22673,2021-04-18,Alabama,270,345.00,7.04,0,11.14,0.23

In [4]:
cols = data.columns.tolist()
cols

['date',
 'state',
 'cases',
 'cases_avg',
 'cases_avg_per_100k',
 'deaths',
 'deaths_avg',
 'deaths_avg_per_100k']

In [5]:
cols = [cols[1]] + [cols[0]] + cols[2:]
cols

['state',
 'date',
 'cases',
 'cases_avg',
 'cases_avg_per_100k',
 'deaths',
 'deaths_avg',
 'deaths_avg_per_100k']

In [6]:
data = data[cols] 
data

,state,date,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,Washington,2020-01-21,1,0.14,0.00,0,0.00,0.00
1,Washington,2020-01-22,0,0.14,0.00,0,0.00,0.00
2,Washington,2020-01-23,0,0.14,0.00,0,0.00,0.00
3,Washington,2020-01-24,0,0.14,0.00,0,0.00,0.00
4,Illinois,2020-01-24,1,0.14,0.00,0,0.00,0.00
...,...,...,...,...,...,...,...,...
22669,California,2021-04-18,1610,2510.14,6.35,45,82.14,0.21
22670,Arkansas,2021-04-18,45,185.57,6.15,1,4.71,0.16
22671,Arizona,2021-04-18,711,600.00,8.24,2,11.50,0.16
22672,Alaska,2021-04-18,0,161.57,22.09,0,0.17,0.02
22673,Alabama,2021-04-18,270,345.00,7.04,0,11.14,0.23

In [7]:
data = data.rename(columns={"state": "id"})
data

,id,date,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,Washington,2020-01-21,1,0.14,0.00,0,0.00,0.00
1,Washington,2020-01-22,0,0.14,0.00,0,0.00,0.00
2,Washington,2020-01-23,0,0.14,0.00,0,0.00,0.00
3,Washington,2020-01-24,0,0.14,0.00,0,0.00,0.00
4,Illinois,2020-01-24,1,0.14,0.00,0,0.00,0.00
...,...,...,...,...,...,...,...,...
22669,California,2021-04-18,1610,2510.14,6.35,45,82.14,0.21
22670,Arkansas,2021-04-18,45,185.57,6.15,1,4.71,0.16
22671,Arizona,2021-04-18,711,600.00,8.24,2,11.50,0.16
22672,Alaska,2021-04-18,0,161.57,22.09,0,0.17,0.02
22673,Alabama,2021-04-18,270,345.00,7.04,0,11.14,0.23

In [11]:
num = data._get_numeric_data()

num[num < 0] = 0

data

,id,date,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,Washington,2020-01-21,1,0.14,0.00,0,0.00,0.00
1,Washington,2020-01-22,0,0.14,0.00,0,0.00,0.00
2,Washington,2020-01-23,0,0.14,0.00,0,0.00,0.00
3,Washington,2020-01-24,0,0.14,0.00,0,0.00,0.00
4,Illinois,2020-01-24,1,0.14,0.00,0,0.00,0.00
...,...,...,...,...,...,...,...,...
22669,California,2021-04-18,1610,2510.14,6.35,45,82.14,0.21
22670,Arkansas,2021-04-18,45,185.57,6.15,1,4.71,0.16
22671,Arizona,2021-04-18,711,600.00,8.24,2,11.50,0.16
22672,Alaska,2021-04-18,0,161.57,22.09,0,0.17,0.02
22673,Alabama,2021-04-18,270,345.00,7.04,0,11.14,0.23

In [12]:
data.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/CovidDataMatrix.csv', index = False)

In [13]:
data_states = data["id"]
data_states = set(data_states)
data_states = list(data_states)

In [14]:
data_var = list(data.columns[2:])
data_var = [data_var[2]]
data_var

['cases_avg_per_100k']

In [15]:
states = data_states
variables = data_var

df = pd.DataFrame()

for i in range(len(states)):
    state = data.loc[data['id'] == ""+states[i]]
    newdf = state.iloc[0:1]
    
    for j in range(len(variables)):
        variable_name = variables[j]
        for k in range(state.shape[0]):
            var_name = str(k)
            value = state.iloc[k][""+variable_name]
            newdf[var_name+variable_name] = value
    
    df = pd.concat([df, newdf], ignore_index=True)
    
df

<ipython-input-15-f237a6595f77>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf[var_name+variable_name] = value

,id,date,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k,0cases_avg_per_100k,1cases_avg_per_100k,...,444cases_avg_per_100k,445cases_avg_per_100k,446cases_avg_per_100k,447cases_avg_per_100k,448cases_avg_per_100k,449cases_avg_per_100k,450cases_avg_per_100k,451cases_avg_per_100k,452cases_avg_per_100k,453cases_avg_per_100k
0,Alabama,2020-03-13,6,0.86,0.02,0,0.00,0.00,0.02,0.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Missouri,2020-03-07,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Florida,2020-03-01,2,0.29,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Puerto Rico,2020-03-13,3,0.43,0.01,0,0.00,0.00,0.01,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Connecticut,2020-03-08,1,0.14,0.00,0,0.00,0.00,0.00,0.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Montana,2020-03-13,4,0.57,0.05,0,0.00,0.00,0.05,0.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Minnesota,2020-03-06,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Vermont,2020-03-07,1,0.14,0.02,0,0.00,0.00,0.02,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,District of Columbia,2020-03-07,1,0.14,0.02,0,0.00,0.00,0.02,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Iowa,2020-03-08,3,0.43,0.01,0,0.00,0.00,0.01,0.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Kansas,2020-03-07,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Mississippi,2020-03-11,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Kentucky,2020-03-06,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Texas,2020-02-12,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,New Hampshire,2020-03-02,1,0.14,0.01,0,0.00,0.00,0.01,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Oregon,2020-02-28,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,West Virginia,2020-03-17,1,0.14,0.01,0,0.00,0.00,0.01,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,New Jersey,2020-03-04,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,North Dakota,2020-03-11,1,0.14,0.02,0,0.00,0.00,0.02,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Nevada,2020-03-05,2,0.29,0.01,0,0.00,0.00,0.01,0.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Pennsylvania,2020-03-06,2,0.29,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Maine,2020-03-12,1,0.14,0.01,0,0.00,0.00,0.01,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,South Carolina,2020-03-06,2,0.29,0.01,0,0.00,0.00,0.01,0.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Maryland,2020-03-05,3,0.43,0.01,0,0.00,0.00,0.01,0.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Guam,2020-03-15,3,0.43,0.25,0,0.00,0.00,0.25,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Virginia,2020-03-07,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Massachusetts,2020-02-01,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Washington,2020-01-21,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,14.06,14.29,14.34,14.86,15.59,15.43,16.08,16.66,17.51,17.5
28,Idaho,2020-03-13,1,0.14,0.01,0,0.00,0.00,0.01,0.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Colorado,2020-03-05,2,0.29,0.00,0,0.00,0.00,0.00,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Oklahoma,2020-03-06,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Indiana,2020-03-06,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,North Carolina,2020-03-03,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Hawaii,2020-03-06,1,0.14,0.01,0,0.00,0.00,0.01,0.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Delaware,2020-03-11,1,0.14,0.01,0,0.00,0.00,0.01,0.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Northern Mariana Islands,2020-03-28,2,0.29,0.53,0,0.00,0.00,0.53,0.53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Illinois,2020-01-24,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,26.42,26.67,26.44,26.28,26.11,25.61,25.36,NaN,NaN,NaN
37,South Dakota,2020-03-10,5,0.71,0.08,1,0.14,0.02,0.08,0.13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Alaska,2020-03-12,1,0.14,0.02,0,0.00,0.00,0.02,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Arkansas,2020-03-11,1,0.14,0.00,0,0.00,0.00,0.00,0.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Tennessee,2020-03-05,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Utah,2020-02-25,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Nebraska,2020-02-17,10,1.43,0.07,0,0.00,0.00,0.07,0.07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Wisconsin,2020-02-05,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Ohio,2020-03-09,3,0.43,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Wyoming,2020-03-11,1,0.14,0.02,0,0.00,0.00,0.02,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Virgin Islands,2020-03-14,1,0.14,0.13,0,0.00,0.00,0.13,0.13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Louisiana,2020-03-09,1,0.14,0.00,0,0.00,0.00,0.00,0.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,California,2020-01-25,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,7.79,7.82,7.74,7.45,7.18,6.35,NaN,NaN,NaN,NaN
49,New York,2020-03-01,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Rhode Island,2020-03-01,2,0.29,0.03,0,0.00,0.00,0.03,0.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Michigan,2020-03-10,2,0.29,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Arizona,2020-01-26,1,0.14,0.00,0,0.00,0.00,0.00,0.00,...,8.55,8.06,8.57,7.91,8.24,NaN,NaN,NaN,NaN,NaN
53,New Mexico,2020-03-11,4,0.57,0.03,0,0.00,0.00,0.03,0.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Georgia,2020-03-02,2,0.29,0.00,0,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_data = df.fillna(0)

In [17]:
df_data = df_data.drop(columns = list(data.columns))
df_data

,0cases_avg_per_100k,1cases_avg_per_100k,2cases_avg_per_100k,3cases_avg_per_100k,4cases_avg_per_100k,5cases_avg_per_100k,6cases_avg_per_100k,7cases_avg_per_100k,8cases_avg_per_100k,9cases_avg_per_100k,...,444cases_avg_per_100k,445cases_avg_per_100k,446cases_avg_per_100k,447cases_avg_per_100k,448cases_avg_per_100k,449cases_avg_per_100k,450cases_avg_per_100k,451cases_avg_per_100k,452cases_avg_per_100k,453cases_avg_per_100k
0,0.02,0.03,0.07,0.08,0.11,0.15,0.23,0.29,0.35,0.39,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
1,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.02,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
2,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.01,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
3,0.01,0.02,0.02,0.02,0.02,0.02,0.03,0.05,0.07,0.08,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4,0.00,0.01,0.01,0.01,0.02,0.04,0.08,0.10,0.16,0.26,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
5,0.05,0.08,0.08,0.11,0.11,0.16,0.25,0.20,0.31,0.37,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
6,0.00,0.00,0.01,0.01,0.01,0.01,0.02,0.03,0.05,0.08,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
7,0.02,0.02,0.02,0.02,0.05,0.05,0.05,0.09,0.16,0.25,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
8,0.02,0.02,0.08,0.08,0.20,0.20,0.20,0.30,0.32,0.36,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
9,0.01,0.04,0.06,0.06,0.07,0.08,0.08,0.09,0.06,0.07,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
10,0.00,0.00,0.00,0.00,0.00,0.02,0.03,0.03,0.04,0.05,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
11,0.00,0.00,0.03,0.03,0.05,0.06,0.10,0.16,0.24,0.36,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
12,0.00,0.00,0.01,0.02,0.02,0.02,0.04,0.03,0.05,0.05,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
13,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
14,0.01,0.02,0.02,0.02,0.02,0.04,0.04,0.03,0.03,0.03,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
15,0.00,0.00,0.01,0.01,0.01,0.01,0.01,0.00,0.02,0.04,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
16,0.01,0.02,0.04,0.06,0.10,0.13,0.13,0.30,0.39,0.57,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
17,0.00,0.00,0.01,0.01,0.01,0.02,0.02,0.04,0.04,0.07,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
18,0.02,0.02,0.02,0.02,0.02,0.02,0.09,0.11,0.34,0.49,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
19,0.01,0.01,0.01,0.02,0.02,0.02,0.03,0.04,0.08,0.09,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
20,0.00,0.00,0.01,0.01,0.01,0.02,0.02,0.04,0.05,0.07,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
21,0.01,0.02,0.03,0.13,0.18,0.34,0.46,0.54,0.58,0.71,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
22,0.01,0.01,0.02,0.02,0.02,0.03,0.03,0.03,0.05,0.06,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
23,0.01,0.01,0.01,0.01,0.01,0.02,0.03,0.02,0.04,0.06,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
24,0.25,0.25,0.25,0.68,1.02,1.19,1.27,2.03,2.20,2.46,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
25,0.00,0.00,0.01,0.01,0.02,0.03,0.05,0.07,0.07,0.08,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
26,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
27,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,14.06,14.29,14.34,14.86,15.59,15.43,16.08,16.66,17.51,17.5
28,0.01,0.04,0.04,0.04,0.07,0.09,0.18,0.24,0.30,0.34,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
29,0.00,0.02,0.02,0.02,0.03,0.04,0.08,0.12,0.17,0.24,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
30,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.01,0.01,0.03,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
31,0.00,0.00,0.00,0.01,0.01,0.02,0.03,0.02,0.03,0.04,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
32,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.02,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
33,0.01,0.01,0.02,0.02,0.02,0.02,0.02,0.01,0.03,0.05,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
34,0.01,0.06,0.06,0.06,0.10,0.12,0.23,0.37,0.38,0.51,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
35,0.53,0.53,0.53,0.53,1.59,2.12,2.12,1.59,1.59,1.59,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
36,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,26.42,26.67,26.44,26.28,26.11,25.61,25.36,0.00,0.00,0.0
37,0.08,0.13,0.13,0.15,0.15,0.15,0.16,0.10,0.05,0.10,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
38,0.02,0.02,0.02,0.02,0.06,0.12,0.18,0.21,0.25,0.39,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
39,0.00,0.03,0.03,0.04,0.08,0.10,0.10,0.15,0.27,0.44,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
40,0.00,0.00,0.00,0.01,0.01,0.01,0.02,0.04,0.05,0.06,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
41,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
42,0.07,0.07,0.07,0.08,0.08,0.08,0.08,0.01,0.02,0.02,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
43,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
44,0.00,0.00,0.00,0.01,0.02,0.03,0.05,0.06,0.08,0.11,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
45,0.02,0.02,0.05,0.07,0.07,0.25,0.37,0.39,0.42,0.49,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
46,0.13,0.13,0.27,0.27,0.40,0.40,0.81,0.67,2.15,2.02,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
47,0.00,0.02,0.04,0.04,0.11,0.24,0.32,0.42,0.58,0.82,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
48,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,7.79,7.82,7.74,7.45,7.18,6.35,0.00,0.00,0.00,0.0
49,0.00,0.00,0.00,0.01,0.02,0.03,0.07,0.08,0.10,0.13,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
50,0.03,0.03,0.03,0.03,0.03,0.04,0.04,0.01,0.01,0.04,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
51,0.00,0.00,0.02,0.04,0.05,0.08,0.08,0.09,0.11,0.46,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
52,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,8.55,8.06,8.57,7.91,8.24,0.00,0.00,0.00,0.00,0.0
53,0.03,0.04,0.07,0.09,0.12,0.14,0.16,0.16,0.20,0.22,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
54,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.02,0.03,0.04,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0

In [18]:
#df_data = df_data.drop(columns = data_var)
#df_data

In [19]:
#df_data = df_data.drop(['id', 'date'], axis=1)

In [20]:
df_num = df_data.to_numpy().T

In [21]:
df_num

array([[0.02, 0.  , 0.  , ..., 0.  , 0.03, 0.  ],
       [0.03, 0.  , 0.  , ..., 0.  , 0.04, 0.  ],
       [0.07, 0.  , 0.  , ..., 0.  , 0.07, 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ]])

In [22]:
for i in range(7):
    noc_val = i + 1
    XC, S, C, SSE, varexpl = PCHA(df_num, noc=noc_val, I = None, delta=0)
    
    S_df = pd.DataFrame(S)
    XC_df = pd.DataFrame(XC)
    
    S_df.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/CovidSMatrix'+ \
                str(noc_val)+'.csv', index = False, header = True)
    XC_df.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/CovidXCMatrix'+ \
                 str(noc_val)+'.csv', index = False, header = True)

In [45]:
COVID_small = data
COVID_Week = COVID_small[(COVID_small['date'] > '2021-01-07') & (COVID_small['date'] < '2021-01-11')]
COVID_Week

,id,date,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
17119,Northern Mariana Islands,2021-01-08,0,0.43,0.80,0,0.00,0.00
17120,Guam,2021-01-08,13,10.43,6.19,1,0.29,0.17
17121,Puerto Rico,2021-01-08,2169,716.14,21.14,4,10.14,0.30
17122,Virgin Islands,2021-01-08,0,0.86,0.81,0,0.00,0.00
17123,Wyoming,2021-01-08,479,319.71,55.24,0,7.29,1.26
...,...,...,...,...,...,...,...,...
17279,California,2021-01-10,42413,42276.29,107.00,301,480.71,1.22
17280,Arkansas,2021-01-10,3330,3085.86,102.26,33,42.00,1.39
17281,Arizona,2021-01-10,6646,8880.29,122.00,58,154.29,2.12
17282,Alaska,2021-01-10,254,298.43,40.79,0,1.14,0.16
17283,Alabama,2021-01-10,2750,4280.86,87.31,35,65.86,1.34

In [39]:
COVID_Week.to_csv('/Users/markomiholjcic/Documents/GitHub/ArchetypalAnalysis/data/CovidWeekDataMatrix.csv', index = False)